apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/HoussemDhahri/Tetris-app-End-to-End-Project.git
    targetRevision: main
    path: Kubernetes-Manifests-file/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: tetris-prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true