grafana:
  enabled: true

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: standard

  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local:80
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    retention: 10d

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: standard
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true