grafana:
  enabled: true

  persistence:
    enabled: true
    storageClassName: standard
    size: 10Gi

prometheus:
  prometheusSpec:
    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true