apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
  labels:
    app: tetris-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tetris-app

  template:
    metadata:
      labels:
        app: tetris-app
        
    spec:
      containers:
        - name: tetris
          image: houssemdhahri93/tetris

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "512m"
              memory: "250Mi"
            limits:
              cpu: "1Gi"
              memory: "500Mi"
